### ISSUE TITLE
::target pseudo-class

### ISSUE THREAD

**Issue by walkerab** [giakki/uncss#117]
Any CSS rules with a `::target` pseudo class selector are removed.

I think it would be a more sensible default to leave them in as long as everything before the `:` checks out.

e.g.

``` html
<h2 class="section-title">Hello</h2>
```

``` css
.section-title:target {
    color: green;
}
```

Keep the CSS rule since `.section-title` matches.
