### ISSUE TITLE
Can UnCSS optimise selectors?

### ISSUE THREAD

**Issue by ben-eb** [giakki/uncss#141]
I'm posting this here because I think this could be an important optimisation; whether it's right for UnCSS or not I don't know. Seems to me that if this behaviour were to be created in a separate module, many of that module's optimisation goals would be the same as UnCSS.

One of UnCSS's benefits is that, unlike other CSS optimisation tools, it _knows_ about the state of the DOM, and therefore can actually remove unused parts of the CSS files. A minifier on the other hand, may be able to combine selectors and dedupe properties, but it always has to assume that the author's intended selectors are correct for the DOM that they have.

Consider this example. It's from Bootstrap:

``` css
.label-default[href]:focus, .label-default[href]:hover {
    background-color: #0f1c3d;
}
```

The authors of Bootstrap have written that selector so that if an `a` tag with the `label-default` class on it _does not_ have a `href` attribute on it, hovering over it will not change its visual presentation. But more often than not, the `a` tag will have the attribute on it. UnCSS could check whether that is or is not the case; if it were to analyse _all_ these selectors to check that they had the attribute, the selector could then be condensed down to this:

``` css
.label-default:focus, .label-default:hover {
    background-color: #0f1c3d;
}
```

Similarly, consider this example:

``` css
h1 a span {
    font-size: 0.8em;
}
```

If UnCSS can test that the only existence of a `span` inside a `h1` is inside of an `a` element, and there are no instances where `<h1>Some text <span>some small text</span></h1>` occur, then it could optimise this selector to:

``` css
h1 span {
    font-size: 0.8em;
}
```

There's a whole load of use cases here, when parsing large frameworks that necessarily have very specific selectors, one of the most important optimisations in my opinion is to trim those selectors down, because you know the exact state of the DOM, whereas the framework authors do not.

And as an added bonus, trimming selectors down will increase rendering performance.
