### ISSUE TITLE
Inline ignore comments issue

### ISSUE THREAD

**Issue by alanontheweb** [giakki/uncss#149]
I'm trying to use `/* uncss:ignore */`, but with nested elements in Sass, the comment gets moved to the top of the parent selector, which does not work. If I manually move it back in the exported css, it works fine.

Another example is when I used nested media queries - the output is this:

```css
/* uncss:ignore */
@media only screen and (max-width: 47.9375rem) {
  .page-document.expanded {
    padding-left: 3.75rem; } }

@media only screen and (min-width:48rem) {
  .page-document.expanded {
    padding-left: 8.125rem; } }

@media only screen and (min-width:75.0625rem) {
  .page-document.expanded {
    padding-left: 9.6875rem; } }
```

Besides adding the ignored classes in the gulp config or rewriting my selectors in Sass, is there anything that can be done about this to persist the comment line on Sass output?

**Comment by ben-eb** [comment]
Does Sass move comments marked as important? e.g:

```scss
/**! important comment */
@media only screen and (max-width: 47.9375rem) {
.page-document.expanded {
padding-left: 3.75rem; } }
```

If so you might be interested in this patch, try replacing the uncss install in the gulp plugin with that one. https://github.com/giakki/uncss/pull/148
