### ISSUE TITLE
URL normalization

### ISSUE THREAD

**Issue by szepeviktor** [giakki/uncss#156]
How could URLs be normalized?

`http://chrisdry.wp/wp-content/themes/scribe/css/../fonts/Pe-icon-7-stroke.eot`

**Comment by giakki** [comment]
Not sure what you're asking. Is UnCSS reporting some errors? If you're fetching resources over the network, it should be able to find them without any help :)

**Comment by szepeviktor** [comment]
If the css contains `..\` uncss leaves it in the absolute URL.


-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!

**Comment by ben-eb** [comment]
I don't think this should be UnCSS's responsibility; that should be up to a CSS minifier.

**Comment by szepeviktor** [comment]
I would agree....

This site http://refresh-sf.com/ has YUI and CleanCSS. None of them normalizes the relative URL.
Do you know any minifier that does it?

**Comment by szepeviktor** [comment]
```css
a {
    background: url(http://chrisdry.wp/wp-content/themes/scribe/css/../fonts/Pe-icon-7-stroke.eot);
}
```
