### ISSUE TITLE
property missing error on valid css

### ISSUE THREAD

**Issue by cyberwombat** [giakki/uncss#160]
I am getting a `property missing` error on the following which I believe is valid css:

```css
@media print {
  @page {
    #fc {   /* <-- */
      size: auto;
      margin-left: 2cm;
      margin-right: 2cm;
    }
  }
}
```
