### ISSUE TITLE
Animation keyframes that are referenced in a chain are removed

### ISSUE THREAD

**Issue by tprobinson** [giakki/uncss#188]
It appears that animation keyframes that are only ever referenced as part of a chain are not recognized as being 'used'. Example is from Effeckt.css:
```css
.effeckt-list[data-effeckt-type='pop-in'] .new-item {
  max-height: 0;
  opacity: 0;
  transform: translateX(-300px);
  animation: openSpace 500ms ease forwards, moveIn 750ms 500ms ease forwards; }

@keyframes openSpace {
  to {
    max-height: 50px; } }

@keyframes moveIn { /* this was removed without explicit ignore */
  to {
    opacity: 1;
    transform: translateX(0); } }
```

Specifying `/moveIn/` in ignore works to keep the keyframes in.
