### ISSUE TITLE
use uncss:ignore to ignore a whole block of css rules

### ISSUE THREAD

**Issue by michaelWalter** [giakki/uncss#300]
I have the problem that the /* uncss:ignore */ will only apply to the next css rule.
I am using uncss after compiling my sass-files with compass.

So this (made up sass file):
```sass
/* uncss:ignore */
.recently-viewed-products {
    font-weight:bold;
    #recently-viewed-preview {
        font-weight: normal
    }
}
```

Will become this after the sass-compilation:
```css
/* uncss:ignore */
.recently-viewed-products {
    font-weight:bold;
}
.recently-viewed-products #recently-viewed-preview {
    font-weight:normal;
}
```

Which means that only `.recently-viewed-products` will be ignore but `.recently-viewed-products #recently-viewed-preview` won't.

Is it maybe possible to extend the `/* uncss:ingnore */` to something like `/* uncss:ingnore start */` and `/* uncss:ignore end */` ?

In this case, I could use it to ignore all my external plugins without prefixing everything, changing the classes in the DOM and modifying their JS-files.
