### ISSUE TITLE
0.7.6 issue with protocol relative URL

### ISSUE THREAD

**Issue by XhmikosR** [giakki/uncss#36]
Not sure if this is an issue or not... With 0.7.5 it didn't happen. With 0.7.6 my css includes this

``` css
@font-face{font-family:'Open Sans';font-style:normal;font-weight:400;src:local('Open Sans'),local('OpenSans'),url(http://themes.googleusercontent.com/static/fonts/opensans/v7/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf) format('truetype')}@font-face{font-family:'Open Sans';font-style:normal;font-weight:700;src:local('Open Sans Bold'),local('OpenSans-Bold'),url(http://themes.googleusercontent.com/static/fonts/opensans/v7/k3k702ZOKiLJc3WVjuplzInF5uFdDttMLvmWuJdhhgs.ttf) format('truetype')}@font-face{font-family:'Open Sans';font-style:italic;font-weight:400;src:local('Open Sans Italic'),local('OpenSans-Italic'),url(http://themes.googleusercontent.com/static/fonts/opensans/v7/xjAJXh38I15wypJXxuGMBp0EAVxt0G0biEntp43Qt6E.ttf) format('truetype')}
```

which is because I have

``` html
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,400italic,700">
```

But I'm not sure this makes sense to include it since it beats the point of using the google fonts.
