### ISSUE TITLE
Implement support for warnings on duplication across similar selectors

### ISSUE THREAD

**Issue by jrcryer** [giakki/uncss#4]
Used to identify duplication across modular CSS selectors. Possible scenario occurs with larger products and a team is responsible for each module.

``` css
.sports header {
    color: #333;
    font-weight: normal;
    font-size: 1.2em;
}

.politics header {
    color: #333;
    font-weight: normal;
    font-size: 1.2em;
}
```

A warning could be flagged and suggest a more abstract module applied. This might conflict with the use of mixins with pre-processors.
