### ISSUE TITLE
Detect unused css custom properties (aka variables)

### ISSUE THREAD

**Issue by paulirish** [giakki/uncss#520]
Repro on the https://uncss-online.com/ page:

```html
<div>sdlfkj</div>
```

```css
::root {
  --reddish: red;
  --unused: cornflowerblue;
}
div { color: var(--reddish); }
span { color: blue; }
```

### results 
```css
::root {
  --reddish: red;
  --unused: cornflowerblue;
}
div { color: var(--reddish); }
```

Would love for `--unused` to be detected and flagged.
