### ISSUE TITLE
Implement support for detection of duplication across media queries

### ISSUE THREAD

**Issue by jrcryer** [giakki/uncss#55]
This would be a nice feature to detect duplication across media queries.  For example:

``` css
#header {
   color: #000;
   font-size: 1em;
}

@media screen and (min-width:320px) {
    #header {
        color: #000;
        font-size: 2.4em;
    }
}
```

The color property would be flagged as duplicated.  This is pretty tricky and it might be unachievable due to the order in which the media query is applied and the front-end strategy used to deliver the responsive experience.
