### ISSUE TITLE
options.ignore removes .classname but keeps @keyframes classname?

### ISSUE THREAD

**Issue by t1mmen** [giakki/uncss#77]
Hi,

I originally reported this issue at https://github.com/addyosmani/grunt-uncss/issues/114, but it appears to be an issue with uncss, rather than grunt-uncss. The original bug report follows. I'll be happy to reproduce using only uncss, just let me know :)
## 

Using `options.ignore = ['slideInLeft']` in my `Gruntfile.js`, it appears to preserve the @keyframes name, but remove the classname if both are identical (as they are in animate.css)

Relevant output without uncss:

``` css
@keyframes slideInLeft {
  0% {
    opacity: 0;
    -webkit-transform: translateX(-2000px);
    -ms-transform: translateX(-2000px);
    transform: translateX(-2000px);
  }
  100% {
    -webkit-transform: translateX(0);
    -ms-transform: translateX(0);
    transform: translateX(0);
  }
}
.slideInLeft {
  -webkit-animation-name: slideInLeft;
  animation-name: slideInLeft;
}
```

Output using uncss:

``` css
@keyframes slideInLeft {
  0% {
    opacity: 0;
    -webkit-transform: translateX(-2000px);
    -ms-transform: translateX(-2000px);
    transform: translateX(-2000px);
  }
  100% {
    -webkit-transform: translateX(0);
    -ms-transform: translateX(0);
    transform: translateX(0);
  }
}
/* missing .sideInLeft! */
```

Since `.slideInLeft` is added via JS on my page, I also tried including the classname in the static HTML, with the same result.
## 

This was using grunt-uncss 0.3.5, which is uses uncss 0.8.1.
